export const f = {
  UI_RESIZED: "UI_RESIZED",
  SET_GRAVITY: "SET_GRAVITY",
  SET_MASS: "SET_MASS",
  SET_TIME_STEP: "SET_TIME_STEP",
  SET_FRICTION: "SET_FRICTION",
  SET_PARTICLE_RADIUS: "SET_PARTICLE_RADIUS",
  RESET_SIMULATION: "RESET_SIMULATION",
  RUN_SIMULATION: "RUN_SIMULATION",
  SELECT_TERRAIN: "SELECT_TERRAIN",
  SELECT_OBSTACLES: "SELECT_OBSTACLES",
  VISIBILITY_POINTS: "VISIBILITY_POINTS",
  VISIBILITY_PATHS: "VISIBILITY_PATHS",
} as const;
